/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { types, } from "./shared/bootstrap.dto";
export namespace Components {
    interface BxAlert {
        "alert": () => Promise<boolean>;
        "close": () => Promise<void>;
        "dismissible": boolean;
        "dispose": () => Promise<void>;
        "message"?: string;
        "type": types;
    }
    interface BxBadge {
        "content": string;
        "link"?: string;
        "pill": boolean;
        "target": string;
        "type": types;
    }
}
declare global {
    interface HTMLBxAlertElement extends Components.BxAlert, HTMLStencilElement {
    }
    var HTMLBxAlertElement: {
        prototype: HTMLBxAlertElement;
        new (): HTMLBxAlertElement;
    };
    interface HTMLBxBadgeElement extends Components.BxBadge, HTMLStencilElement {
    }
    var HTMLBxBadgeElement: {
        prototype: HTMLBxBadgeElement;
        new (): HTMLBxBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "bx-alert": HTMLBxAlertElement;
        "bx-badge": HTMLBxBadgeElement;
    }
}
declare namespace LocalJSX {
    interface BxAlert {
        "dismissible"?: boolean;
        "message"?: string;
        "onClosed"?: (event: CustomEvent<void>) => void;
        "onClosing"?: (event: CustomEvent<void>) => void;
        "type"?: types;
    }
    interface BxBadge {
        "content"?: string;
        "link"?: string;
        "pill"?: boolean;
        "target"?: string;
        "type"?: types;
    }
    interface IntrinsicElements {
        "bx-alert": BxAlert;
        "bx-badge": BxBadge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bx-alert": LocalJSX.BxAlert & JSXBase.HTMLAttributes<HTMLBxAlertElement>;
            "bx-badge": LocalJSX.BxBadge & JSXBase.HTMLAttributes<HTMLBxBadgeElement>;
        }
    }
}
