/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AdditionalVariants, ButtonSizes, Variants, } from "./shared/bootstrap.dto";
export namespace Components {
    interface BxAlert {
        "alert": () => Promise<boolean>;
        "close": () => Promise<void>;
        "dismissible": boolean;
        "dispose": () => Promise<void>;
        "text"?: string;
        "variant": Variants;
    }
    interface BxBadge {
        "link"?: string;
        "pill": boolean;
        "target"?: string;
        "text"?: string;
        "variant": Variants;
    }
    interface BxButton {
        "active": boolean;
        "block": boolean;
        "disabled": boolean;
        "dispose": () => Promise<void>;
        "link"?: string;
        "outline": boolean;
        "size": ButtonSizes;
        "target"?: string;
        "text": string;
        "toggle": () => Promise<void>;
        "variant": AdditionalVariants | Variants;
    }
}
declare global {
    interface HTMLBxAlertElement extends Components.BxAlert, HTMLStencilElement {
    }
    var HTMLBxAlertElement: {
        prototype: HTMLBxAlertElement;
        new (): HTMLBxAlertElement;
    };
    interface HTMLBxBadgeElement extends Components.BxBadge, HTMLStencilElement {
    }
    var HTMLBxBadgeElement: {
        prototype: HTMLBxBadgeElement;
        new (): HTMLBxBadgeElement;
    };
    interface HTMLBxButtonElement extends Components.BxButton, HTMLStencilElement {
    }
    var HTMLBxButtonElement: {
        prototype: HTMLBxButtonElement;
        new (): HTMLBxButtonElement;
    };
    interface HTMLElementTagNameMap {
        "bx-alert": HTMLBxAlertElement;
        "bx-badge": HTMLBxBadgeElement;
        "bx-button": HTMLBxButtonElement;
    }
}
declare namespace LocalJSX {
    interface BxAlert {
        "dismissible"?: boolean;
        "onClosed"?: (event: CustomEvent<void>) => void;
        "onClosing"?: (event: CustomEvent<void>) => void;
        "text"?: string;
        "variant"?: Variants;
    }
    interface BxBadge {
        "link"?: string;
        "pill"?: boolean;
        "target"?: string;
        "text"?: string;
        "variant"?: Variants;
    }
    interface BxButton {
        "active"?: boolean;
        "block"?: boolean;
        "disabled"?: boolean;
        "link"?: string;
        "outline"?: boolean;
        "size"?: ButtonSizes;
        "target"?: string;
        "text"?: string;
        "variant"?: AdditionalVariants | Variants;
    }
    interface IntrinsicElements {
        "bx-alert": BxAlert;
        "bx-badge": BxBadge;
        "bx-button": BxButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bx-alert": LocalJSX.BxAlert & JSXBase.HTMLAttributes<HTMLBxAlertElement>;
            "bx-badge": LocalJSX.BxBadge & JSXBase.HTMLAttributes<HTMLBxBadgeElement>;
            "bx-button": LocalJSX.BxButton & JSXBase.HTMLAttributes<HTMLBxButtonElement>;
        }
    }
}
