/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { types, } from "./components/bootstrap-alert/bootstrap-dto";
export namespace Components {
    interface BootstrapAlert {
        "alert": () => Promise<boolean>;
        "close": () => Promise<void>;
        "dismissible": boolean;
        "dispose": () => Promise<void>;
        "message": string;
        "type": types;
    }
}
declare global {
    interface HTMLBootstrapAlertElement extends Components.BootstrapAlert, HTMLStencilElement {
    }
    var HTMLBootstrapAlertElement: {
        prototype: HTMLBootstrapAlertElement;
        new (): HTMLBootstrapAlertElement;
    };
    interface HTMLElementTagNameMap {
        "bootstrap-alert": HTMLBootstrapAlertElement;
    }
}
declare namespace LocalJSX {
    interface BootstrapAlert {
        "dismissible"?: boolean;
        "message"?: string;
        "onClosed"?: (event: CustomEvent<void>) => void;
        "onClosing"?: (event: CustomEvent<void>) => void;
        "type"?: types;
    }
    interface IntrinsicElements {
        "bootstrap-alert": BootstrapAlert;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bootstrap-alert": LocalJSX.BootstrapAlert & JSXBase.HTMLAttributes<HTMLBootstrapAlertElement>;
        }
    }
}
